"""empty message

Revision ID: 74c15020ddba
Revises: ed657e16ce20
Create Date: 2017-10-14 19:45:52.372000

"""

# revision identifiers, used by Alembic.
revision = '74c15020ddba'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
